### ISSUE TITLE
GPLv3 Or Any Later Version

### ISSUE THREAD

**Issue by scott-martinez** [mrloam/informatic#13]
Hello, can you please change "Informatic can be used and distributed under the terms of the GNU General Public License, version 3" to say "Informatic can be used and distributed under the terms of the GNU General Public License, either version 3 of the License, or (at your option) any later version." Otherwise it has an incompatibility with GPLv4 (and 5 and 6, and etc.) since it doesn't provide an upgrade path for compatibility with code that people put under future GPL versions. Plan for decades. Thanks!

**Comment by mrloam** [comment]
Done.
